extern "C" {

#define SUPERSONIC_STUB(name) int name(...) { return -1; }

SUPERSONIC_STUB(dotcache_qwen35_hip_rms_norm)
SUPERSONIC_STUB(dotcache_qwen35_hip_cast)
SUPERSONIC_STUB(dotcache_qwen35_hip_element_add)
SUPERSONIC_STUB(dotcache_qwen35_hip_apply_rope_prefill)
SUPERSONIC_STUB(dotcache_qwen35_hip_transpose_shd_hsd)
SUPERSONIC_STUB(dotcache_qwen35_hip_sigmoid_mul)
SUPERSONIC_STUB(dotcache_qwen35_hip_compute_beta_g)
SUPERSONIC_STUB(dotcache_qwen35_hip_split_qgate)
SUPERSONIC_STUB(dotcache_qwen35_hip_split_qkv)
SUPERSONIC_STUB(dotcache_qwen35_hip_repeat_interleave_heads)
SUPERSONIC_STUB(dotcache_qwen35_hip_transpose_pad_conv)
SUPERSONIC_STUB(dotcache_qwen35_hip_extract_conv_state)
SUPERSONIC_STUB(dotcache_qwen35_hip_fused_rms_norm_linear)
SUPERSONIC_STUB(dotcache_qwen35_4b_hip_matmul_rhs_transposed_tiled)
SUPERSONIC_STUB(dotcache_qwen35_4b_hip_matmul_fp8_dequant)
SUPERSONIC_STUB(dotcache_qwen35_4b_hip_matmul_int4_dequant)
SUPERSONIC_STUB(dotcache_qwen35_4b_hip_quantize_kv_to_fp8)
SUPERSONIC_STUB(dotcache_qwen35_hip_embedding_lookup)
SUPERSONIC_STUB(dotcache_qwen35_hip_batched_matmul)
SUPERSONIC_STUB(dotcache_qwen35_hip_full_attention_prefill)
SUPERSONIC_STUB(dotcache_qwen35_hip_full_attention_decode_flat)
SUPERSONIC_STUB(dotcache_qwen35_hip_full_attention_decode_flat_strided)
SUPERSONIC_STUB(dotcache_qwen35_4b_hip_matmul_int8)
SUPERSONIC_STUB(dotcache_qwen35_4b_hip_int8_outlier_add)
SUPERSONIC_STUB(dotcache_qwen35_hip_linear_prefill_conv_pack)
SUPERSONIC_STUB(dotcache_qwen35_hip_delta_recurrent_prefill)
SUPERSONIC_STUB(dotcache_qwen35_hip_l2norm)
SUPERSONIC_STUB(dotcache_qwen35_hip_swiglu_mul)
SUPERSONIC_STUB(dotcache_qwen35_hip_rms_norm_gated)
SUPERSONIC_STUB(dotcache_qwen35_hip_mul_scalar)
SUPERSONIC_STUB(dotcache_qwen35_4b_hip_linear_decode_apply)
SUPERSONIC_STUB(dotcache_qwen35_4b_hip_linear_stateful_conv_value_decay)

#undef SUPERSONIC_STUB

}
