"""Generate token-budget-controlled prompts for the SpecPrefill TTFT sweep.

The R1 sweep used /tmp/qwen36_specprefill_prompt_*.txt which were never
archived in-tree and got wiped. We regenerate equivalents using the
Qwen3.6 tokenizer so future runs are reproducible.
"""
import sys
from tokenizers import Tokenizer

TOKENIZER_DIR = "/mnt/data/models/Qwen3.6-35B-A3B"
TARGETS = {
    "c0088": 88,
    "c0349": 349,
    "c1393": 1393,
    "c4177": 4177,
    "c8353": 8353,
}

# Source text — deterministic, AI/transformer-themed (matches R1 prompt
# topical domain). Generated by manual composition; not copied from any
# copyrighted source.
BASE = """\
The history of artificial intelligence began in antiquity with myths and stories about artificial beings. Over the centuries it evolved through philosophical inquiry, mathematical formalism in the twentieth century, and finally the practical breakthroughs of machine learning in the twenty-first. Today the field is dominated by large neural networks trained on enormous datasets. Looking ahead, the next decade is likely to bring transformative changes across science, medicine, engineering, education, and creative work. The transformer architecture has revolutionized natural language processing through its self-attention mechanism, allowing models to weigh the importance of different parts of the input sequence dynamically. Unlike recurrent networks, transformers can process all tokens in parallel during training, making them highly efficient on modern accelerator hardware. The attention computation involves three projections — query, key, and value — followed by a softmax-normalized dot product that produces a weighted combination of value vectors. Multi-head attention extends this by performing several attention operations in parallel across different learned subspaces, then concatenating and projecting the results. Feed-forward networks between attention layers introduce non-linearity and per-token transformation. Residual connections and layer normalization stabilize gradients during training. The overall result is a sequence of contextually enriched representations that downstream layers can specialise. Mixture-of-experts variants further improve scaling efficiency by routing each token to a small subset of expert sub-networks rather than activating the full feed-forward block, lowering FLOPs per token while preserving model capacity. Speculative decoding accelerates inference by running a smaller draft model alongside the target and verifying drafted tokens in parallel; speculative prefill applies the same idea to the prefill phase, scoring prompt tokens with a drafter and pruning unimportant positions. Long-context modelling has driven research into sparse attention, sliding-window attention, and KV-cache compression, all aimed at sublinear memory and time growth. Quantisation — INT8, INT4, FP8 — has matured into the dominant deployment-time technique for fitting frontier models onto commodity hardware. The interplay between hardware (matrix-multiply throughput, memory bandwidth, on-chip SRAM) and algorithmic choices (attention shape, expert routing, draft acceptance) is now the central question for systems researchers. """

def main():
    tok = Tokenizer.from_file(f"{TOKENIZER_DIR}/tokenizer.json")
    out_dir = sys.argv[1] if len(sys.argv) > 1 else "."
    for tag, target in TARGETS.items():
        text = BASE
        while len(tok.encode(text).ids) < target * 1.5:
            text = text + BASE
        ids = tok.encode(text).ids
        if len(ids) > target:
            text = tok.decode(ids[:target])
            sp = text.rfind(" ")
            if sp > len(text) * 0.95:
                text = text[:sp] + " "
        actual = len(tok.encode(text).ids)
        path = f"{out_dir}/specprefill_{tag}_target{target}_actual{actual}.txt"
        with open(path, "w") as f:
            f.write(text)
        print(f"{tag}: target={target} actual={actual} chars={len(text)} path={path}")

if __name__ == "__main__":
    main()
